In [54]:
import pandas as pd


fl = pd.read_excel('Test_data_with_truth_labels.xltx')

/usr/local/lib/python3.7/dist-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")

In [55]:
fl

                                                 Tweet  Threat  G/S
0    وزیراعل ی پنجاب کا ضلع راولپنڈی کا دورہ لینڈسل...       0    2
1    الحمدلله پورے پاکستان کے وکلاء برادری کا کہنا ...       1    1
2       جنوری مہلت ختم الٹی گنتی شروع  ن لیگ کے خلا...       1    1
3    کروناکی آڑ میں حکومت اورفوج جوکھیل قادیانیوں ک...       1    1
4    حکومت ایکشن میں آئے ورنہ اگر ہم ایکشن میں آگئے...       1    1
..                                                 ...     ...  ...
930  کوئ اور کے پیڈ جیالوں کو بتا دے عمران احمد خان...       1    1
931  مجبور نہ کرو کے لوگ قانون ہاتھ میں لیں دین اسل...       1    1
932  یہ ڈرامہ اور سیاست کریں گے یہ زلیل اور گهٹیا ل...       0    2
933  وزیراعظم صاحب آپ کا یہ اتنی جلد بازی کا فیصلہ ...       0    2
934  ہمارا ملک ہے   ہم تو پوچھیں گے    جواب دو   مل...       0    2

[935 rows x 3 columns]

In [56]:
count1 = (fl['Threat'] == 0).sum()
count2 = (fl['Threat'] == 1).sum()

count3 = (fl['G/S'] == 0).sum()
count4 = (fl['G/S'] == 1).sum()
count5 = (fl['G/S'] == 2).sum()


print('Non-Threatening Tweets: ', count1)
print('Threatening Tweets: ', count2)
print('Tweets that target Individuals: ',count3)
print('Tweets that target Group (s): ', count4)
print('Non-Threatening Tweets: ', count5)


print('Total Number of Tweets: ', count1 +  count2)

Non-Threatening Tweets:  628
Threatening Tweets:  307
Tweets that target Individuals:  56
Tweets that target Group (s):  251
Non-Threatening Tweets:  628
Total Number of Tweets:  935